name: piczzie
description: Piczzie for iOS

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  camera: ^0.5.7+3
  image_cropper: ^1.2.0
  path_provider: 1.5.1
  path: ^1.6.4
  image_crop: ^0.3.2
  http: 0.12.0+2
  flutter_bloc: ^2.1.1
  connectivity: ^0.4.3+2
  built_value: ^6.7.0
  get_it: ^3.0.3
  equatable: ^1.0.1
  shared_preferences: ^0.5.6
  intl: ^0.16.0
  intl_translation: ^0.17.6
  custom_navigator: ^0.3.0
  dio: ^3.0.8
  json_annotation: ^3.0.0
  json_serializable: ^3.2.5
  cached_network_image: ^2.0.0
  torch: ^0.1.1
  permission: ^0.1.5
  http_parser: ^3.1.3
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_cupertino_localizations: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner :

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - resources/assets/6443.jpg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Picons
       fonts:
         - asset: resources/fonts/Plain.ttf

     - family: Gift
       fonts:
         - asset: resources/fonts/Gift.ttf

     - family: FavoriteHeartButton
       fonts:
         - asset: resources/fonts/FavoriteHeartButton.ttf

     - family: favoriteHeart
       fonts:
         - asset: resources/fonts/FavoriteHeart.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
